# Composite action for e2e tests.
name: Run E2E Test
description: Run e2e test using the minikube cluster

inputs:
  experiments:
    required: true
    description: comma delimited experiment name
  training-operator:
    required: false
    description: whether to deploy training-operator or not
    default: false
  trial-images:
    required: true
    description: comma delimited trial image name
  katib-ui:
    required: true
    description: whether to deploy katib-ui or not
    default: false
  database-type:
    required: false
    description: mysql or postgres
    default: mysql

runs:
  using: composite
  steps:
    - name: Setup Minikube Cluster
      shell: bash
      run: ./test/e2e/v1beta1/scripts/gh-actions/setup-minikube.sh ${{ inputs.katib-ui }} ${{ inputs.trial-images }} ${{ inputs.experiments }}

    - name: Setup Katib
      shell: bash
      run: ./test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh ${{ inputs.katib-ui }} ${{ inputs.training-operator }} ${{ inputs.database-type }}

    - name: Run E2E Experiment
      shell: bash
      run: ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.sh ${{ inputs.experiments }}
