name: Go Test

on:
  pull_request:
    paths-ignore:
      - "pkg/ui/v1beta1/frontend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generatetests:
    name: Generate And Format Test
    runs-on: ubuntu-22.04
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/katib
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/kubeflow/katib

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ${{ env.GOPATH }}/src/github.com/kubeflow/katib/go.mod

      - name: Check Go Modules, Generated Go/Python codes, and Format
        run: make check

  unittests:
    name: Unit Test
    runs-on: ubuntu-22.04
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/katib
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/kubeflow/katib

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ${{ env.GOPATH }}/src/github.com/kubeflow/katib/go.mod

      - name: Run Go test
        run: go mod download && make test ENVTEST_K8S_VERSION=${{ matrix.kubernetes-version }}

      - name: Coveralls report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
          working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/katib

    strategy:
      fail-fast: false
      matrix:
        # Detail: `setup-envtest list`
        kubernetes-version: ["1.25.0", "1.26.1", "1.27.1"]
